### ISSUE TITLE
Formatting and progression issues.

### ISSUE THREAD

**Issue by theelous3** [akulakov/pythontut#2]
This tutorial uses code examples that are completely impenetrable to a new programmer.

    questions = [
        [
         'How can I get input form a user in Python?',
         'input()'
         ],

        [
         'How can I assign to a variable?',
         '='
         ],
        ]

Not only is this bad programming style, but as a point of first contact for a new person it's overly complex in a multitude of ways. What actually is a list? Why is there two lists in  a list? Why is there a trailing ,?

The second piece of code is a for loop with unpacking. Seriously?
```
for question, right_answer in questions:
        user_answer = input(question)
        if user_answer == right_answer:
            print('Surely a lucky guess')
        else:
            print('You erred')
```
How on earth is any new person going to figure out that they're unpacking lists from inside a list? If they're not supposed to figure this out, why is it there at all?

Next up we have a grab-bag of language features, like comparisons and for loops and a function, all of which are not very related to each other and none of which are explained in any meaningful way.

> A few things to note:
> 
> - `for` command goes over our questions in a list, one by one.
> - `=` operator assigns to a variable.
> - `==` operator checks if something is equal to another thing.
> - `if` command does an action if two things are equal.
> - `print()` command displays given text to the screen

For example, you say the `=` operator assigns to a variable. What is an operator? What is a variable? Why would you assign something to a variable? What can you assign to a variable?

The lists section doesn't even give an example of a list.

The adding more questions section presumes a new person either
1. Knows how to append a list to a list
2. Is able to mentally parse the first code example.

These are bad presumptions.

The next two sections start making programs and importing things with no regard for what prior knowledge the noob might have, and the rest of the tutorial degrades rapidly from then on, in to madness with tetris games and such.

Please rethink the *entire* strategy of this tutorial before sending it to new people.

**Comment by akulakov** [comment]
Per discussion on IRC, tutorial is meant for students who know basics of Python; added an intro section with links to official python tutorial.
